FROM openjdk:17-slim
RUN apt-get update && apt-get install -y findutils

WORKDIR /app

COPY gradlew gradlew
COPY gradle gradle
COPY build.gradle build.gradle
COPY settings.gradle settings.gradle

RUN ./gradlew dependencies --no-daemon || true

ENTRYPOINT ["./gradlew", "bootRun", "--no-daemon"]